### PR TITLE
Add image render sensor and in device tracker

### LINKED ISSUE #2: [Feature] Add image of car as icon to device_tracker
[Original issue in old repository](https://github.com/Prior99/myskoda/issues/1#issue-2514325473) by @sonar98.

In the Skodaconnect version the device_tracker icon shows the image that is available from the API.

image

I think this part of the code in the `init.py` is getting this image:

    if "position" in self.attribute:
        # Try to use small thumbnail first hand, else fallback to fullsize
        if self.vehicle.is_model_image_small_supported:
            attributes["entity_picture"] = self.vehicle.model_image_small
        elif self.vehicle.is_model_image_large_supported:
            attributes["entity_picture"] = self.vehicle.model_image_large

    return attributes

### PR DESCRIPTION
**Pull request by dvx76**
Fixes #2

### CODE REVIEW

**Review by WebSpider — COMMENTED** [review]
#2 is about adding the render to the device tracker, i dont see the setting of a `picture` in the `device_tracker` here?

**Comment by sonar98** [comment]
the part in device_tracker.py starting at line 84 is adding the image

**Review by WebSpider — APPROVED** [review]
Lets wait for the linter to pass before merging it

**Comment by WebSpider** [comment]
> the part in device_tracker.py starting at line 84 is adding the image:
> 
> attributes["entity_picture"]

Learn something new every day about HA. I thought it was the `picture` property of the `device_tracker`.

**Comment by WebSpider** [comment]
@dvx76 if you rebase / merge main the linter should pass.

**Comment by dvx76** [comment]
rebased

**Pull request merged**
