### PR TITLE
Prevent integration from stalling when MQTT does not connect

### PR DESCRIPTION
**Pull request by WebSpider**
In a service disruption we have seen MQTT become unavailable.
Since we by default await the presence of the MQTT service, this blocks the integration from starting.

This PR changes behaviour in a subtle manner:
- The integration will initialise with only polling present
- As soon as regular updates are scheduled, we enable MQTT listening as well

### CODE REVIEW

**Comment by WebSpider** [comment]
Tested, and this works.
Downside of this approach is that MQTT only gets connected after we do our first scheduled poll, which by default is 30m after integration initialization

**Comment by dvx76** [comment]
> Downside of this approach is that MQTT only gets connected after we do our first scheduled poll, which by default is 30m after integration initialization

I don't love that 🤔 . Could we not enable mqtt directly after the `coordinator.async_config_entry_first_refresh()` call?

BTW what happens if MQTT is unavailable when `enable_mqtt()` is called? Does it also block? Would that mean that we'd get into the exact same situation (stalled) on the first normal pull after 30m?

**Comment by WebSpider** [comment]
> > Downside of this approach is that MQTT only gets connected after we do our first scheduled poll, which by default is 30m after integration initialization
> 
> I don't love that 🤔 . Could we not enable mqtt directly after the `coordinator.async_config_entry_first_refresh()` call?

We'd be in the same boat. If connecting MQTT cause significant delay in `async_setup`, we don't finish setting up the integration.

> BTW what happens if MQTT is unavailable when `enable_mqtt()` is called? Does it also block? Would that mean that we'd get into the exact same situation (stalled) on the first normal pull after 30m?

Yeah, we would. This is why I've made it a seperate async task, so we:
1- Attempt to connect when we don't have an active connection
2- Are outside the main init loop while doing this

**Comment by WebSpider** [comment]
Just tested this, and MQTT connection is now out of the main loop (initial poll and mqtt connection are done simultaneously according to timestamps)

```
2024-12-06 12:02:26.198 DEBUG (MainThread) [myskoda.myskoda] IDK Authorization was successful.
2024-12-06 12:02:26.198 DEBUG (MainThread) [myskoda.myskoda] Myskoda ready.
2024-12-06 12:02:26.584 DEBUG (MainThread) [custom_components.myskoda.coordinator] Connecting to MQTT.
2024-12-06 12:02:26.585 DEBUG (MainThread) [custom_components.myskoda.coordinator] Performing scheduled update of all data for vin MYVIN
2024-12-06 12:02:27.275 INFO (MainThread) [myskoda.mqtt] Connecting to MQTT with UID/['MYVIN']
2024-12-06 12:02:27.275 DEBUG (MainThread) [myskoda.mqtt] Starting _connect_and_listen
2024-12-06 12:02:27.455 DEBUG (SyncWorker_3) [myskoda.mqtt] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k15) client_id=b''
2024-12-06 12:02:27.486 DEBUG (MainThread) [myskoda.mqtt] Received CONNACK (0, 0)
2024-12-06 12:02:27.486 INFO (MainThread) [myskoda.mqtt] Connected to MQTT
2024-12-06 12:02:27.489 DEBUG (MainThread) [myskoda.mqtt] Sending SUBSCRIBE (d0, m1) [(b'UID/MYVIN/operation-request/air-conditioning/set-air-conditioning-at-unlock', 0)]
2024-12-06 12:02:27.517 DEBUG (MainThread) [myskoda.mqtt] Received SUBACK
...
2024-12-06 12:02:28.975 DEBUG (MainThread) [myskoda.mqtt] Received SUBACK
2024-12-06 12:02:48.665 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 22.082 seconds (success: True)
2024-12-06 12:02:49.021 INFO (MainThread) [homeassistant.components.sensor] Setting up myskoda.sensor
2024-12-06 12:02:49.023 DEBUG (MainThread) [custom_components.myskoda.coordinator] Performing scheduled update of all data for vin MYVIN
2024-12-06 12:02:49.032 INFO (MainThread) [homeassistant.setup] Setting up device_tracker
2024-12-06 12:02:49.033 INFO (MainThread) [homeassistant.setup] Setup of domain device_tracker took 0.00 seconds
2024-12-06 12:02:49.034 INFO (MainThread) [homeassistant.components.device_tracker] Setting up myskoda.device_tracker
2024-12-06 12:02:49.036 INFO (MainThread) [homeassistant.setup] Setting up climate
2024-12-06 12:02:49.040 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.00 seconds
2024-12-06 12:02:49.041 INFO (MainThread) [homeassistant.components.climate] Setting up myskoda.climate
2024-12-06 12:02:49.043 INFO (MainThread) [homeassistant.components.switch] Setting up myskoda.switch
2024-12-06 12:02:49.049 INFO (MainThread) [homeassistant.setup] Setting up number
2024-12-06 12:02:49.050 INFO (MainThread) [homeassistant.setup] Setup of domain number took 0.00 seconds
2024-12-06 12:02:49.051 INFO (MainThread) [homeassistant.components.number] Setting up myskoda.number
2024-12-06 12:02:49.052 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2024-12-06 12:02:49.053 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.00 seconds
2024-12-06 12:02:49.053 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up myskoda.binary_sensor
2024-12-06 12:02:49.060 INFO (MainThread) [homeassistant.setup] Setting up image
2024-12-06 12:02:49.062 INFO (MainThread) [homeassistant.setup] Setup of domain image took 0.00 seconds
2024-12-06 12:02:49.063 INFO (MainThread) [homeassistant.components.image] Setting up myskoda.image
2024-12-06 12:02:49.065 INFO (MainThread) [homeassistant.setup] Setting up lock
2024-12-06 12:02:49.065 INFO (MainThread) [homeassistant.setup] Setup of domain lock took 0.00 seconds
2024-12-06 12:02:49.066 INFO (MainThread) [homeassistant.components.lock] Setting up myskoda.lock
2024-12-06 12:02:49.068 INFO (MainThread) [homeassistant.setup] Setting up button
2024-12-06 12:02:49.068 INFO (MainThread) [homeassistant.setup] Setup of domain button took 0.00 seconds
2024-12-06 12:02:49.069 INFO (MainThread) [homeassistant.components.button] Setting up myskoda.button
2024-12-06 12:02:59.022 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform myskoda is taking over 10 seconds.
2024-12-06 12:03:04.538 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 15.516 seconds (success: True)
2024-12-06 12:03:04.542 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 48.04s
2024-12-06 12:03:04.543 INFO (MainThread) [homeassistant.core] Starting Home Assistant
```

**Review by dvx76 — APPROVED** [review]

**Pull request merged**
