### PR TITLE
Handle marketing consent error in integration

### PR DESCRIPTION
**Pull request by WebSpider**
This adds integration handling for the new `MarketingConsentError` introduced in myskoda v0.15.4

### CODE REVIEW

**Review by prvakt — APPROVED** [review]
lgtm

**Comment by UZi02** [comment]
Hello!  

Apologies for bringing this issue up again. I’ve installed the latest version 1.19.1, and when I enter my email and password, I encounter an error. The logs provide the following details:  

```
This error originated from a custom integration

Logger: custom_components.myskoda.config_flow  
Source: custom_components/myskoda/config_flow.py:111  
Integration: MySkoda (Documentation, Issues)  
First occurred: January 24, 2025, 23:58:02 (3 occurrences)  
Last logged: 00:04:05  

Unexpected exception  
Traceback (most recent call last):  
  File "/config/custom_components/myskoda/config_flow.py", line 111, in async_step_user  
    await validate_input(self.hass, user_input)  
  File "/config/custom_components/myskoda/config_flow.py", line 67, in validate_input  
    await hub.connect(data["email"], data["password"])  
  File "/usr/local/lib/python3.13/site-packages/myskoda/myskoda.py", line 130, in connect  
    await self.authorization.authorize(email, password)  
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 77, in authorize  
    self.idk_session = await self._get_idk_session()  
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 224, in _get_idk_session  
    authentication = await self._enter_password(login_meta)  
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 167, in _enter_password  
    raise MarketingConsentError(location)  
myskoda.auth.authorization.MarketingConsentError: https://identity.vwgroup.io/signin-service/v1/consent/marketing/be678393-faec-4452-aee3-61d2911f6acf/7f045eee-7003-4379-9968-9355ed2adb06@apps_vw-dilab_com/0?relayState=138519ce24b449a4cde904e85170a8923278f405&hmac=5195dc33b3ceb6d09b1833737171335e1a0c7e22dccf99ad4e2a6e40921420e4&callback=https://identity.vwgroup.io/oidc/v1/oauth/client/callback/success?user_id%3Dbe678393-faec-4452-aee3-61d2911f6acf%26client_id%3D7f045eee-7003-4379-9968-9355ed2adb06@apps_vw-dilab_com%26scopes%3Daddress%2520badge%2520birthdate%2520cars%2520driversLicense%2520dealers%2520email%2520mileage%2520mbb%2520nationalIdentifier%2520openid%2520phone%2520profession%2520profile%2520vin%26consentedScopes%3Daddress%2520badge%2520birthdate%2520cars%2520driversLicense%2520dealers%2520email%2520mileage%2520mbb%2520nationalIdentifier%2520openid%2520phone%2520profession%2520profile%2520vin%26relayState%3D138519ce24b449a4cde904e85170a8923278f405%26hmac%3Dba9d95aa379a1dbef19f6986e4bc714c982f3c559f16c32dc30c1c51b1bcff16  
```  

Am I doing something wrong?  

Thank you!

**Comment by WebSpider** [comment]
Please log out of the app, log in again and go through the new t&c or marketing settings.

**Comment by UZi02** [comment]
Thank you for the suggestion! Logging out and back into the app resolved the issue for me. However, it would be helpful if the error message explicitly mentioned this step to guide users more effectively.

**Comment by WebSpider** [comment]
It was the intention a repair issue would be raised in HA for this, explaining what to do. If you did not get it, that would be a bug

**Comment by UZi02** [comment]
Indeed, I had just installed the integration for the very first time, and the error message was quite general. Unfortunately, since the issue is now resolved, I can’t provide any further details about the error message.

**Pull request merged**
