### PR TITLE
Initial implementation of reauthentication flow

### PR DESCRIPTION
**Pull request by WebSpider**
Reauthentication is triggered when initial login fails.
Needs real-world testing still

### CODE REVIEW

**Review by dvx76 — APPROVED** [review]
LGTM. Pending real-world test

**Comment by WebSpider** [comment]
Tested in real world. Functionally works, but gives this warning:

```
2024-11-14 01:13:34.584 WARNING (MainThread) [homeassistant.config_entries] Detected reauth config flow creating a new entry, when it is expected to update an existing entry and abort. This will stop working in 2025.11, please create a bug report at https://github.com/skodaconnect/homeassistant-myskoda/issues
```

**Comment by WebSpider** [comment]
Gah, stupid linter.

**Comment by dvx76** [comment]
@WebSpider are you still working on this one?

**Comment by WebSpider** [comment]
Hope to make some time for this over the holiday, but if you have something ready, dont let me stop you

**Comment by WebSpider** [comment]
This is too out of sync. I will rework this and submit a new PR.

**Pull request closed without merging**
