### PR TITLE
Fix InvalidCapabilityConfigurationError exceptions

### LINKED ISSUE #49: bad capability configuration for all entitys
After upgrade to 1.4.2  all entity's are  in state "not provided". my car is Enyaq 85x
Log file: 
[home-assistant_2024-09-29T15-09-07.722Z.log](https://github.com/user-attachments/files/17179856/home-assistant_2024-09-29T15-09-07.722Z.log)
In the log file I can see that the skoda server is reporting  "INSUFFICIENT_BATTERY_LEVEL" for almost all capabillities.... 
But should that stop the integration?   
myskoda app is working but after a while show the "battery protection message". the car shows no alerts, 12v battery voltage is 13.2v...

### PR DESCRIPTION
**Pull request by dvx76**
Instead of raising an uncaught exception in the entities when the underlying attributes in the MySkoda Vehicle object are (temporarily) missing (None), just return None. HA will show the entities as Unknown.

Fixes #49

Discord discussion: https://discord.com/channels/877164727636230184/1087487796731707402/1295108867755081800

Still need to test this but wanted to get the PR up.

### CODE REVIEW

**Comment by WebSpider** [comment]
Also fixes #73

**Comment by WebSpider** [comment]
Also fixes #72

**Comment by WebSpider** [comment]
Please have a look at the linter. Code runs fine on my dev install.

**Comment by dvx76** [comment]
passing checks now, minor changes to pass pyright and other linters

**Review by WebSpider — APPROVED** [review]
Lgtm

**Pull request merged**
